FROM golang:1.21-alpine as builder

WORKDIR /worker

# COPY go.mod, go.sum and download the dependencies
COPY go.* ./
RUN go mod download

# COPY All things inside the project and build
COPY . .
RUN go build -o /worker/google_api_worker .

FROM alpine:latest
COPY --from=builder /worker/google_api_worker /worker/google_api_worker

EXPOSE 8080
ENTRYPOINT [ "/google_api_worker" ]
